---
DEFAULTS: &DEFAULTS
  database: <%= ENV['PURVIEW_DBNAME'] %>
  username: <%= ENV['PURVIEW_USERNAME'] %>
  password: <%= ENV['PURVIEW_PASSWORD'] %>
postgres:
  <<: *DEFAULTS
  host: <%= ENV['PURVIEW_POSTGRESQL_HOST'] %>
  port: <%= ENV['PURVIEW_POSTGRESQL_PORT'] %>
mysql:
  <<: *DEFAULTS
  host: <%= ENV['PURVIEW_MYSQL_HOST'] %>
  port: <%= ENV['PURVIEW_MYSQL_PORT'] %>
